In [1]:
import pandas as pd
import numpy as np
file=pd.read_csv('C:\\Users\\zhou\\Desktop\\train.csv')
file1=pd.read_csv('C:\\Users\\zhou\\Desktop\\test.csv')
file2=pd.read_csv('C:\\Users\\zhou\\Desktop\\gender_submission.csv')
data_train=file.loc[0:,['Pclass','Sex','Age','SibSp','Parch','Fare']]
data_train_label=file.loc[0:,'Survived']
data_test=file1.loc[0:,['Pclass','Sex','Age','SibSp','Parch','Fare']]
data_test_label=file2.iloc[0:,0:]
count=0
for i in data_train.loc[0:,'Sex']:
    count+=1
    if i=='female':
        data_train.loc[0:,'Sex'][count-1]=0
    if i=='male':
        data_train.loc[0:,'Sex'][count-1]=1
count=0
for i in data_test.loc[0:,'Sex']:
    count+=1
    if i=='female':
        data_test.loc[0:,'Sex'][count-1]=0
    if i=='male':
        data_test.loc[0:,'Sex'][count-1]=1
data_others=np.array(data_train)[0:,[0,1,3,4,5]]
data_age=np.array(data_train)[0:,[2]]
data_test_others=np.array(data_test)[0:,[0,1,3,4,5]]
data_test_age=np.array(data_test)[0:,[2]]
nan_index_list=[]
for i in range(891):
    if pd.isnull(data_age[i][0]):
        nan_index_list.append(i)  
nan_test_index_list=[]
for i in range(418):
    if pd.isnull(data_test_age[i][0]):
        nan_test_index_list.append(i) 
#归一化处理
data_others=(data_others-data_others.min(axis=0))/(data_others.max(axis=0)-data_others.min(axis=0))
data_test_others=(data_test_others-data_test_others.min(axis=0))/(data_test_others.max(axis=0)-data_test_others.min(axis=0))
#利用knn算法补充age的缺失值
def knn(nums,data_others,k,data_age):
    data_size=data_others.shape[0]
    diffmat=np.tile(data_others[nums],(data_size,1))-data_others
    diffmat_sqr=diffmat**2
    sqrdiff=diffmat_sqr.sum(axis=1)
    distance_set=sqrdiff**0.5
    distance_sort=np.argsort(distance_set)
    list_near_average=[]
    for i in range(k):
        list_near_average.append(distance_sort[i])
    average=[]
    for i in list_near_average:
        average.append(data_age[i][0])
    average_new=[]
    for i in average:
        if pd.notnull(i):
            average_new.append(i)
    return sum(average_new)/len(average_new)
for nums in nan_index_list:
    data_train.loc[0:,'Age'][nums]=knn(nums,data_others,10,data_age)
for nums1 in nan_test_index_list:
    data_test.loc[0:,'Age'][nums1]=knn(nums1,data_test_others,10,data_test_age)
data_train=np.array(data_train)
data_train_label=np.array(data_train_label)
data_test=np.array(data_test)
data_test_label=np.array(data_test_label)
data_test_label=data_test_label[0:,1]
list_one=[]
for i in range(891):
    list_one.append(1)
list_one1=[]
for i in range(418):
    list_one1.append(1)
one=np.array(list_one)
one=one.reshape(891,1)
one1=np.array(list_one1).reshape(418,1)
data_train=np.hstack((one,data_train))
data_test=np.hstack((one1,data_test))

C:\Users\zhou\anaconda3\lib\site-packages\numpy\core\_methods.py:34: RuntimeWarning: invalid value encountered in reduce
  return umr_minimum(a, axis, None, out, keepdims, initial, where)
C:\Users\zhou\anaconda3\lib\site-packages\numpy\core\_methods.py:30: RuntimeWarning: invalid value encountered in reduce
  return umr_maximum(a, axis, None, out, keepdims, initial, where)


In [2]:
data_train[0:,3]=(data_train[0:,3]-min(data_train[0:,3]))/(max(data_train[0:,3])-min(data_train[0:,3]))

In [3]:
data_train[0:,6]=(data_train[0:,6]-min(data_train[0:,6]))/(max(data_train[0:,6])-min(data_train[0:,6]))

In [4]:
data_test[0:,3]=(data_test[0:,3]-min(data_test[0:,3]))/(max(data_test[0:,3])-min(data_test[0:,3]))
data_test[0:,6]=(data_test[0:,6]-min(data_test[0:,6]))/(max(data_test[0:,6])-min(data_test[0:,6]))

In [5]:
data_train[0:,1]=(data_train[0:,1]-min(data_train[0:,1]))/(max(data_train[0:,1])-min(data_train[0:,1]))
data_test[0:,1]=(data_test[0:,1]-min(data_test[0:,1]))/(max(data_test[0:,1])-min(data_test[0:,1]))

In [6]:
data_train[0:,4]=(data_train[0:,4]-min(data_train[0:,4]))/(max(data_train[0:,4])-min(data_train[0:,4]))
data_test[0:,4]=(data_test[0:,4]-min(data_test[0:,4]))/(max(data_test[0:,4])-min(data_test[0:,4]))

In [7]:
data_train[0:,5]=(data_train[0:,5]-min(data_train[0:,5]))/(max(data_train[0:,5])-min(data_train[0:,5]))
data_test[0:,5]=(data_test[0:,5]-min(data_test[0:,5]))/(max(data_test[0:,5])-min(data_test[0:,5]))

In [8]:
data_train

array([[1, 1.0, 1, ..., 0.125, 0.0, 0.014151057562208049],
       [1, 0.0, 0, ..., 0.125, 0.0, 0.13913573538264068],
       [1, 1.0, 0, ..., 0.0, 0.0, 0.015468569817999833],
       ...,
       [1, 1.0, 0, ..., 0.125, 0.3333333333333333, 0.04577135170121086],
       [1, 0.0, 1, ..., 0.0, 0.0, 0.05855610025741261],
       [1, 1.0, 1, ..., 0.0, 0.0, 0.015126992566498259]], dtype=object)

In [9]:
import random
from random import random
w1=np.random.randn(3,10)
w1

array([[ 0.97110827, -0.35240195, -0.21262329,  1.20854428,  1.61293202,
         0.66675011, -0.41683502,  0.9127177 ,  0.25781168,  1.13306038],
       [-0.66937091,  0.89037831,  0.91078288,  1.63524386,  0.01101084,
         1.57116013, -0.86343   ,  0.49708663, -0.89086705,  0.48416038],
       [-1.29092918, -0.04855354, -1.03589085,  0.76072166, -0.27124996,
         1.36204725, -1.36943692, -0.22826743,  0.81834494,  0.08951741]])

In [49]:
def auto(x,deriv=False):
    if deriv==True:
        return x*(1-x)
    return 1.0/(1.0+np.exp(-x))
def auto_grad(x,a1,a2,y_pred,y,w1,w2,w3):
    delta_y=y-y_pred
    #delta_y=error_y*auto(y_pred,deriv=True)
    
    error_a2=w3.T.dot(delta_y)
    delta_a2=error_a2*auto(a2,deriv=True)

    error_a1=w2.T.dot(delta_a2)
    delta_a1=error_a1*auto(a1,deriv=True)
    return x.dot(delta_a1.T),a1.dot(delta_a2.T),a2.dot(delta_y.T)

In [50]:
def neural_network_2(x,y,maxiter):
    m,n=x.shape
    x=np.array(x,dtype=float)
    y=np.array(y,dtype=float).reshape(m,1)
    w1=np.random.randn(10,n)
    w2=np.random.randn(10,10)
    w3=np.random.randn(1,10)
    x=x.T
    y=y.T
    iter=0
    learn=1/m
    while iter<maxiter:
        iter+=1
        a1=auto(np.dot(w1,x))
        a2=auto(np.dot(w2,a1))
        y_pred=auto(np.dot(w3,a2))
        
        w1_change,w2_change,w3_change=auto_grad(x,a1,a2,y_pred,y,w1,w2,w3)
        
        w1=w1+learn*w1_change.T
        w2=w2+learn*w2_change.T
        w3=w3+learn*w3_change.T
        print(w1_change[0][0])
        
    return w1,w2,w3

In [63]:
w1,w2,w3=neural_network_2(data_train,data_train_label,6000)

-1.3741323296586365
-4.369022084662642
-5.228145612280166
-5.710845302328585
-6.092312443121614
-6.43502475431236
-6.754935035135251
-7.056717259236667
-7.34213926223917
-7.612116874005166
-7.8672327491966225
-8.107877925392193
-8.334299867140663
-8.546627074183618
-8.74488776504997
-8.929027110872758
-9.09892419734282
-9.254409007877372
-9.395279440791533
-9.52131825068477
-9.6323097292589
-9.728055887006231
-9.808391859220057
-9.873200237253295
-9.922424019481117
-9.956077886347316
-9.974257529894626
-9.977146809259082
-9.965022557990189
-9.938256934328559
-9.897317278768515
-9.842763520945244
-9.775243256384714
-9.695484689023319
-9.604287703724358
-9.50251339058651
-9.391072386436566
-9.270912426070973
-9.143005505124135
-9.008335047667744
-8.867883445821207
-8.72262029800766
-8.57349162022283
-8.421410244641377
-8.267247556173468
-8.111826654176445
-7.95591696693271
-7.800230293515932
-7.645418203228422
-7.492070687964446
-7.340715937889261
-7.191821095291217
-7.045793834421638
-6

-0.41607639481449565
-0.4111597736809838
-0.40626367287980614
-0.4013880196171917
-0.39653274038094066
-0.3916977609691257
-0.38688300651848584
-0.3820884015319046
-0.3773138699064136
-0.37255933495998983
-0.36782471945831974
-0.3631099456411562
-0.35841493524834034
-0.35373960954496697
-0.3490838893471202
-0.3444476950459956
-0.3398309466327398
-0.3352335637220647
-0.33065546557604497
-0.326096571127068
-0.32155679900065515
-0.31703606753802926
-0.3125342948178038
-0.3080513986777129
-0.3035872967358286
-0.29914190641121774
-0.2947151449445875
-0.29030692941813196
-0.2859171767753028
-0.2815458038400185
-0.277192727335414
-0.2728578639026269
-0.2685411301188565
-0.26424244251498674
-0.2599617175930984
-0.255698871843435
-0.2514538217611726
-0.24722648386284307
-0.24301677470172445
-0.23882461088422913
-0.23464990908458638
-0.2304925860599507
-0.22635255866488313
-0.22222974386562822
-0.21812405875421703
-0.21403542056131153
-0.20996374667042916
-0.20590895462984804
-0.2018709621659598

0.5580881301581329
0.5585371956329741
0.5589805313243459
0.5594181564614016
0.5598500903447996
0.5602763523455163
0.560696961904815
0.5611119385324086
0.5615213018066201
0.561925071373008
0.5623232669436318
0.5627159082962874
0.5631030152734686
0.5634846077818327
0.5638607057909191
0.5642313293325758
0.5645964984996965
0.5649562334457796
0.5653105543834918
0.5656594815842686
0.5660030353766565
0.5663412361461884
0.5666741043337686
0.5670016604349084
0.567323924998846
0.5676409186274403
0.5679526619739357
0.5682591757426247
0.5685604806870552
0.5688565976093618
0.5691475473593868
0.5694333508330853
0.569714028972351
0.5699896027628251
0.570260093233883
0.5705255214568674
0.5707859085442899
0.5710412756487613
0.5712916439617333
0.5715370347124464
0.5717774691670283
0.5720129686270377
0.5722435544285589
0.5724692479410667
0.572690070566308
0.5729060437369919
0.5731171889158997
0.5733235275945567
0.5735250812921611
0.5737218715544801
0.573913919952521
0.5741012480816217
0.5742838775600596


0.461485711467438
0.4609984648069112
0.4605108654251411
0.460022915088242
0.45953461555407804
0.45904596857208846
0.45855697588406485
0.45806763922369775
0.45757796031736087
0.4570879408835866
0.4565975826339228
0.45610688727265725
0.4556158564973316
0.4551244919984385
0.4546327954599074
0.45414076855959573
0.4536484129686058
0.45315573035200707
0.4526627223692721
0.4521693906733346
0.4516757369122857
0.4511817627280479
0.4506874697573968
0.4501928596319402
0.44969793397810776
0.44920269441734595
0.44870714256636024
0.44821128003709765
0.44771510843697016
0.44721862936908385
0.4467218444319503
0.44622475522035865
0.44572736332462126
0.44522967033150573
0.44473167782356926
0.44423338738008367
0.4437348005764572
0.4432359189848669
0.44273674417396736
0.44223727770932264
0.44173752115322484
0.44123747606516517
0.44073714400152886
0.4402365265159158
0.43973562515927966
0.4392344414799805
0.438732977023816
0.43823123333410496
0.43772921195194536
0.4372269144161427
0.4367243422633824
0.43622

0.2224215019207354
0.22193117959823194
0.2214411377474632
0.22095137710732704
0.22046189841361796
0.219972702397073
0.21948378978567384
0.21899516130200336
0.21850681766589775
0.2180187595924521
0.21753098779302915
0.21704350297503283
0.21655630584167107
0.2160693970926535
0.21558277742316911
0.2150964475248267
0.214610408085111
0.21412465978773554
0.21363920331203357
0.21315403933407762
0.21266916852536966
0.21218459155384162
0.21170030908336424
0.2112163217740184
0.2107326302817749
0.21024923525898886
0.20976613735366412
0.20928333721043835
0.20880083546965666
0.20831863276811258
0.20783672973833456
0.20735512700933034
0.20687382520606046
0.2063928249497935
0.2059121268576547
0.20543173154334826
0.20495163961630025
0.20447185168249704
0.20399236834365975
0.20351319019833847
0.20303431784061132
0.20255575186122465
0.2020774928468625
0.20159954138057068
0.20112189804149372
0.20064456340527093
0.20016753804345777
0.1996908225239653
0.1992144174111412
0.1987383232653659
0.198262540643364

0.03090554105853327
0.03057722307100308
0.030249265320707375
0.02992166779607519
0.029594430485606615
0.029267553377778865
0.02894103646203927
0.02861487972742549
0.02828908316404788
0.027963646761277827
0.02763857051029217
0.027313854400746074
0.02698949842453313
0.026665502571945776
0.02634186683547357
0.026018591205960284
0.02569567567664932
0.025373120239077673
0.025050924886973025
0.024729089612387956
0.02440761440989947
0.024086499272079065
0.023765744194258698
0.023445349169381124
0.023125314193654045
0.022805639260641275
0.02248632436697684
0.022167369507013923
0.02184877467789481
0.02153053987480713
0.021212665095341254
0.02089515033545175
0.02057799559310225
0.020261200865244078
0.01994476615008245
0.0196286914456667
0.01931297675029553
0.01899762206294686
0.01868262738242832
0.01836799270863776
0.0180537180404583
0.017739803378909347
0.01742624872335874
0.01711305407510144
0.016800219434649488
0.01648774480358295
0.016175630183160594
0.01586387557532154
0.015552480982389927


-0.0819789090634957
-0.08214115673282674
-0.08230305056488096
-0.08246459066686929
-0.08262577715203889
-0.08278661012869626
-0.08294708971155873
-0.0831072160101396
-0.08326698914046848
-0.08342640921341982
-0.08358547634625135
-0.08374419065125127
-0.08390255224672583
-0.08406056124665318
-0.08421821777029947
-0.08437552193314479
-0.08453247385558194
-0.08468907365457157
-0.08484532145168378
-0.08500121736523658
-0.0851567615179003
-0.08531195402963898
-0.08546679502420207
-0.08562128462274665
-0.08577542295054008
-0.08592921012994914
-0.08608264628736562
-0.08623573154654807
-0.08638846603547146
-0.08654084987851784
-0.08669288320572921
-0.08684456614208469
-0.08699589881928294
-0.0871468813636167
-0.08729751390761487
-0.0874477965796221
-0.08759772951261158
-0.08774731283665993
-0.08789654668602975
-0.08804543119188923
-0.08819396648989208
-0.08834215271246726
-0.08848998999633184
-0.08863747847547487
-0.08878461828761708
-0.08893140956825674
-0.08907785245633937
-0.089223947088248

-0.07950426545234635
-0.16947523354878546
-0.06974968104956547
-0.18038842667521893
-0.057698601694764484
-0.1938555074642423
-0.042801940666862937
-0.21048869307304185
-0.024376731245002503
-0.2310497088332033
-0.001572882259871733
-0.256486960530641
0.02666846648631571
-0.28798210519628675
0.06166714636006443
-0.32700843238192157
0.10506943887306308
-0.37540409349455395
0.1589302598652771
-0.4354640043068059
0.22581637138692967
-0.510055235310108
0.3089360691367047
-0.6027619439467271
0.41230220508477866
-0.7180674467906072
0.5409371659765241
-0.8615829366023176
0.7011306043426502
-1.040334670436362
0.9007633640247512
-1.2631242125678663
1.149714169295911
-1.5409794529314993
1.4603691573564173
-1.8877173999491084
1.8482578785385821
-2.32064254114288
2.3328420775681566
-2.8614054560040625
2.938483397886204
-3.537042343058415
3.6956088661726336
-4.381201064494116
4.642069930856827
-5.435521149864034
5.824634748031386
-6.751050883677261
7.300431376726371
-8.389411839740678
9.13791123615

11.892588354396185
-12.129197596705662
11.897194751655272
-12.134360143639055
11.903836903136614
-12.141549405232103
11.91245204930064
-12.150701101642992
11.922974970303994
-12.161748498560508
11.935338046114563
-12.174622469479104
11.949471318758283
-12.189251560531186
11.96530255794114
-12.205562059110797
11.982757331241409
-12.223478067473406
12.001759080012711
-12.242921582434217
12.0222292020733
-12.26381258222451
12.044087142185905
-12.286069121482265
12.067250491247586
-12.309607435272179
12.091635095018216
-12.334342052927783
12.11715517311233
-12.360185922405588
12.143723448866979
-12.38705054571968
12.171251290575295
-12.41484612590152
12.199648864443443
-12.443481725789526
12.22882529948432
-12.472865438809702
12.25868886441783
-12.502904571755312
12.289147156482558
-12.533505839409843
12.320107301908326
-12.564575570698324
12.351476167625657
-12.596019925875947
12.383160583625331
-12.627745124100144
12.415067575204539
-12.659657680553467
12.447104604172889
-12.691664652126

12.78815880870032
-12.957801562508864
12.78913994731602
-12.958514963634162
12.79024014462975
-12.959347339508048
12.791456455137833
-12.960295607267849
12.792785650591084
-12.96135640600521
12.79422423708451
-12.962526114162145
12.79576847254117
-12.963800867300975
12.797414384534273
-12.965176576191132
12.799157788388523
-12.96664894515482
12.800994305505121
-12.96821349061306
12.802919381851252
-12.969865559775975
12.804928306560171
-12.971600349420457
12.807016230584434
-12.9734129246986
12.809178185347314
-12.975298237921969
12.811409101337997
-12.977251147267166
12.81370382659819
-12.97926643534931
12.816057145044908
-12.981338827609807
12.81846379458106
-12.983463010468867
12.820918484941108
-12.985633649190758
12.823415915225
-12.987845405414681
12.825950791071136
-12.990092954303625
12.828517841424276
-12.992371001265395
12.831111834853338
-12.994674298202886
12.833727595377502
-12.99699765925224
12.836360017760567
-12.999335975968215
12.839004082235157
-13.00168423192062
12.8

13.132134149309653
-13.23893232719139
13.13359886640281
-13.240184174985027
13.135065619410327
-13.241438502628643
13.136534159135381
-13.242695059660408
13.138004239105928
-13.243953598755118
13.139475616474545
-13.245213876614933
13.140948052878139
-13.24647565481881
13.142421315255628
-13.24773870062875
13.14389517662249
-13.249002787751584
13.145369416798882
-13.250267697052617
13.14684382309024
-13.251533217221628
13.148318190919664
-13.252799145389218
13.149792324410203
-13.25406528769221
13.151266036916105
-13.255331459786968
13.152739151502807
-13.256597487311083
13.15421150137458
-13.257863206292477
13.155682930250617
-13.259128463505128
13.157153292687795
-13.260393116772624
13.158622454352173
-13.261657035219029
13.160090292238271
-13.262920099467467
13.161556694837106
-13.26418220178807
13.163021562254276
-13.265443246194298
13.164484806277532
-13.26670314849084
13.16594635039705
-13.26796183627227
13.167406129777635
-13.26921924887541
13.168864091185725
-13.270475337285502

13.474929390372003
-13.545797109289694
13.47656104365175
-13.547317814272434
13.478193902991546
-13.548840042589854
13.479827971526582
-13.550363796181609
13.481463252682461
-13.55188907726983
13.48309975014949
-13.55341588833376
13.48473746785707
-13.554944232082683
13.486376409946768
-13.556474111429573
13.488016580746214
-13.558005529463715
13.489657984741472
-13.559538489423083
13.491300626549936
-13.561072994667486
13.49294451089358
-13.562609048650973
13.49458964257176
-13.564146654894598
13.496236026434703
-13.565685816960267
13.497883667357208
-13.567226538424181
13.499532570213148
-13.568768822851109
13.501182739850304
-13.570312673769928
13.502834181066154
-13.571858094648952
13.504486898584364
-13.573405088873168
13.506140897032486
-13.574953659721741
13.507796180919993
-13.576503810346784
13.509452754618493
-13.578055543753617
13.511110622341967
-13.579608862781173
13.512769788128761
-13.581163770085222
13.51443025582488
-13.58272026812126
13.516092029068199
-13.58427835912

-13.92982924536466
13.88042593806793
-13.931616907113108
13.882283397476481
-13.933404968058614
13.884141171048597
-13.93519341932727
13.885999250446986
-13.936982252028535
13.887857627313622
-13.938771457255788
13.88971629326958
-13.94056102608684
13.891575239916579
-13.942350949584887
13.893434458836978
-13.944141218798904
13.89529394159478
-13.945931824764383
13.897153679735856
-13.947722758503568
13.899013664788644
-13.94951401102644
13.900873888264828
-13.951305573330865
13.902734341659468
-13.953097436403349
13.90459501645194
-13.954889591219311
13.906455904106009
-13.956682028743497
13.908316996070152
-13.958474739930402
13.910178283778437
-13.960267715724653
13.912039758650323
-13.962060947061351
13.913901412091235
-13.963854424866371
13.915763235492893
-13.965648140056446
13.917625220233504
-13.967442083539929
13.91948735767791
-13.96923624621614
13.92134963917786
-13.971030618976467
13.923212056072359
-13.972825192703864
13.925074599687418
-13.974619958273372
13.9269372613366

-14.313296053236185
14.277621232577031
-14.31495358888212
14.279335653695238
-14.316609568904616
14.28104845781074
-14.31826398572169
14.282759637117499
-14.319916831776505
14.284469183832497
-14.321568099537517
14.286177090196084
-14.323217781498533
14.28788334847211
-14.324865870178789
14.289587950947897
-14.326512358123075
14.291290889934627
-14.328157237902333
14.2929921577675
-14.329800502113041
14.294691746805604
-14.331442143377929
14.296389649432374
-14.333082154345842
14.298085858055543
-14.334720527692136
14.299780365107553
-14.336357256118406
14.301473163045381
-14.33799233235295
14.303164244350771
-14.339625749150757
14.30485360153052
-14.341257499293668
14.306541227116583
-14.342887575590558
14.308227113666137
-14.344515970877465
14.309911253762
-14.34614267801775
14.311593640012225
-14.347767689901964
14.31327426505095
-14.349390999448335
14.314953121537727
-14.351012599602555
14.31663020215841
-14.35263248333824
14.318305499624977
-14.354250643656774
14.319979006675487
-

In [64]:
w1

array([[-1.37968176,  1.94240296, -0.03260812,  5.70547578,  2.21504094,
        -2.66067113,  2.70536316],
       [-2.29897883,  3.92295707,  2.22790616,  0.74439883, -1.12490077,
         0.20038075, -0.50886418],
       [ 0.39727602,  0.92919315, -0.17448817, -1.04399844, -1.29404682,
        -0.55996061, -0.3651784 ],
       [-1.63944934,  1.79537132, -2.26998777, -1.02877916,  2.80996378,
        -0.74567489,  0.33015936],
       [-0.37508034, -3.0888059 ,  1.92175288,  2.40393865, -2.42077668,
        -2.05174979,  0.33625455],
       [ 0.30993521,  0.32650382,  0.20784221, -1.12924574, -2.2572789 ,
         0.12503779,  1.13320023],
       [ 0.954033  ,  0.82154181,  2.3711873 ,  0.73987542,  0.94103935,
        -2.14325069, -1.06081222],
       [-1.89754269,  1.12182293,  1.33915153, -0.39268177,  0.32333087,
        -0.31259816,  0.82579506],
       [ 1.02757044, -0.69880977, -2.67088006,  2.43201283,  0.83805224,
        -2.67337181,  0.96951843],
       [ 0.03207313, -0.2254

In [65]:
w2

array([[ 6.08198117e-02, -1.01371078e-01, -4.66728096e-01,
        -1.44375045e+00,  1.26516391e+00,  9.17953428e-02,
        -2.20770968e-01, -1.62189534e+00, -4.58459441e-01,
        -1.82363251e-01],
       [-1.10864096e+00, -1.07262460e+00,  5.65255694e-01,
         2.84313535e-01, -5.44645351e-01, -9.58856331e-01,
        -1.66274932e+00, -3.58840880e-01, -9.62653080e-03,
        -1.92291444e-02],
       [-7.68800361e-02, -2.52209901e-01,  4.83736255e-01,
         3.69722157e-01, -6.07813570e-02,  1.08741767e+00,
         5.14873279e-01,  2.72361551e+00, -1.81624991e+00,
         1.89862513e+00],
       [ 3.21977385e+00,  2.57284765e+00, -5.45437080e-01,
         1.55111268e+00,  2.83837948e+00, -1.85672661e+00,
        -1.46024024e+00, -4.54405047e-01, -3.93507836e+00,
        -1.57895259e+00],
       [-4.36245230e+00,  1.38184167e+00,  1.09384941e+00,
        -2.56061136e+00, -1.81954176e+00, -4.98677389e-01,
         1.80748654e+00, -3.86357958e-01, -1.98753293e-01,
        -4.

In [66]:
w3

array([[-0.27474176, -1.15162701, -1.85892857, -4.98782659,  3.77131711,
         1.16389171, -0.59261667,  3.00418825,  2.69125829,  2.91825054]])

In [67]:
def neural_pred(data_test,w1,w2,w3):
    data_test=data_test.T
    data_test=np.array(data_test,dtype=float)
    a1=auto(np.dot(w1,data_test))
    a2=auto(np.dot(w2,a1))
    y_pred=auto(np.dot(w3,a2))
    return y_pred

In [68]:
pre=neural_pred(data_test,w1,w2,w3)

In [69]:
pre=pre.tolist()

In [70]:
pre

[[0.07511234755884368,
  0.4903516463518347,
  0.08075792765832572,
  0.09392162491887479,
  0.41284791386935343,
  0.203466729000171,
  0.5524418158065,
  0.07784559007621382,
  0.5899514231712897,
  0.0796207347734839,
  0.09140765165767104,
  0.2575825717842197,
  0.9810498140929028,
  0.09316759457528984,
  0.967710925602873,
  0.9003839984760785,
  0.06406734107050722,
  0.12513805062558858,
  0.4595119663270818,
  0.5607044017711905,
  0.3266051779868817,
  0.4576387726231731,
  0.9735317898588353,
  0.5422794923730874,
  0.9488743342251463,
  0.06653276373874026,
  0.9838932500801874,
  0.11522831605404979,
  0.26786144551010993,
  0.08333170344057783,
  0.07090489712465536,
  0.07805849560201661,
  0.35394936200956195,
  0.42485374979948337,
  0.34895600839899843,
  0.1461293334809115,
  0.567267762731152,
  0.5732927259317995,
  0.10202117392513155,
  0.09036147720718676,
  0.06546890106008502,
  0.26471959750001506,
  0.06761977118449693,
  0.8977832121852196,
  0.96958784342

In [71]:
list_pre=[]
for i in pre[0]:
    if i>=0.5:
        list_pre.append(1)
    if i<0.5:
        list_pre.append(0)

In [72]:
list_pre

[0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,


In [73]:
data_test_label=data_train_label.tolist()

In [74]:
count=0
for i in range(len(list_pre)):
    if list_pre[i]==data_train_label[i]:
        count+=1
print(count/len(list_pre))

0.5419664268585132


In [75]:
import random
import numpy as np

In [76]:
np.random.randn(4,4)

array([[-0.86508835, -0.39820563,  0.67672994, -0.89534399],
       [ 1.61094112, -1.68351123, -0.39667413, -0.15156795],
       [-2.48607977, -1.73214906,  0.77780045, -1.52069425],
       [ 1.4726359 , -0.67998436, -1.72596089,  1.00004176]])

In [ ]:
  delta_y=error_y*auto(y_pred,deriv=True)